---

- name: copy over monitoring.yml
  template:
    src: monitoring.yml.j2
    dest: "{{ docker_runtime_root_dir }}/scripts/monitoring.yml"
    owner: root
    group: root
    mode: 0755
  tags: monitoring

- name: copy over grafana config
  copy: src=grafana.config dest={{ docker_runtime_root_dir }}/grafana.config mode=0755

- name: start docker stack for monitoring
  shell: >
    docker login -u {{ docker_user }} -p {{ docker_password }} {{ docker_repo_host }} && docker stack deploy -c {{ docker_runtime_root_dir }}/scripts/monitoring.yml monitoring --with-registry-auth
  run_once: true
  tags: monitoring