- name: Check Docker compose bin file presence
  stat: path=/usr/bin/docker-compose
  register: dockercompose

- name: Install docker compose
  shell: curl -L -x {{ proxy_url }} https://github.com/docker/compose/releases/download/1.10.1/docker-compose-`uname -s`-`uname -m` > /usr/bin/docker-compose
  when: dockercompose.stat.exists == false

- name: Apply executable permission
  file: path=/usr/bin/docker-compose mode="u+x,g+x"